package main

const (
	flagAddr                 = "addr"
	flagDbName               = "db-name"
	flagDid                  = "did"
	flagHostname             = "hostname"
	flagRotationKeyPath      = "rotation-key-path"
	flagJwkPath              = "jwk-path"
	flagContactEmail         = "contact-email"
	flagRelays               = "relays"
	flagAdminPassword        = "admin-password"
	flagRequireInvite        = "require-invite"
	flagSmtpUser             = "smtp-user"
	flagSmtpPass             = "smtp-pass"
	flagSmtpHost             = "smtp-host"
	flagSmtpPort             = "smtp-port"
	flagSmtpEmail            = "smtp-email"
	flagSmtpName             = "smtp-name"
	flagIpfsNodeUrl          = "ipfs-node-url"
	flagIpfsGatewayUrl       = "ipfs-gateway-url"
	flagSessionSecret        = "session-secret"
	flagSessionCookieKey     = "session-cookie-key"
	flagFallbackProxy        = "fallback-proxy"
	flagLogLevel             = "log-level"
	flagDebug                = "debug"
	flagMetricsListenAddress = "metrics-listen-address"
)
